### ISSUE TITLE
Use skopeo instead of docker to upload images

### ISSUE THREAD

**Issue by Infinisil** [input-output-hk/bitte#16]
For running Nomad jobs ([`run-nomad-job.nix`](https://github.com/input-output-hk/bitte/blob/master/lib/run-nomad-job.nix)), `docker` is used to upload images to the registry. This is a bit annoying though, because one needs a working docker daemon to be able to use it.

An alternative to the `docker` command is [`skopeo`](https://github.com/containers/skopeo), which can interact with Docker registries directly, without a daemon.

The basic primitives needed are:
- `skopeo inspect docker://${registry}/${repo}/${imageName}:${imageTag}` to get info on a specific image
- `skopeo copy docker-archive://$outPath docker://${registry}/${repo}/${imageName}:${imageTag}` to upload a Nix-built Docker image
- `--dest-creds ${username}:${password}` for authentication

I previously used skopeo in this way for building and uploading Docker images from CI, which could be used as reference/inspiration: https://github.com/niteoweb/nix-docker-base/blob/ea0e70cbd075f0bd209b7452ee327f6055fee5fe/scripts/image-update

Ping @manveru
Ping @NinjaTrappeur who earlier had to enable docker, add his user to the docker group and restart the display manager to be able to deploy

**Comment by manveru** [comment]
That sounds awesome, i'd be more than happy if you wanna make a PR. Don't have time right now, but I'll put it on my todo-list anyway if you don't get to it first.

**Comment by manveru** [comment]
This was implemented in https://github.com/input-output-hk/bitte/commit/8c822e79e3a4d6e07f8ccbd05aa809e41d5f3142

**Comment by Infinisil** [comment]
Nice! I believe https://github.com/input-output-hk/bitte/blob/2e82563fdb31ffb5b5c30a786db2cd80a35290c4/lib/run-nomad-job.nix#L100-L104 can be removed as well, removing the need for `docker` in the arguments completely

**Comment by Infinisil** [comment]
Also, skopeo fails to upload images without `/etc/containers/policy.json`:
```
FATA[0000] Error loading trust policy: open /etc/containers/policy.json: no such file or directory
```

The default policy is just insecure though: https://github.com/containers/skopeo/blob/master/default-policy.json

We can pass `--insecure-policy` to make it work without having to have that json file.
